"""Compatibility re-exports for injected runtime dependencies."""

from belief_ledger_core.dependencies import (
    CallableStructuredModel,
    ClockPort,
    FakeStructuredModel,
    FixedClock,
    FixedMonotonicClock,
    IdentityPort,
    MonotonicClockPort,
    RuntimeDependencies,
    SecureIdentity,
    SecureToken,
    SequenceIdentity,
    SequenceToken,
    StructuredModelBudgetError,
    StructuredModelError,
    StructuredModelPort,
    StructuredModelProviderError,
    StructuredModelRequest,
    StructuredModelResult,
    StructuredModelTimeout,
    StructuredModelValidationError,
    SystemClock,
    SystemMonotonicClock,
    TokenPort,
    deterministic_dependencies,
)

__all__ = [
    "CallableStructuredModel",
    "ClockPort",
    "FakeStructuredModel",
    "FixedClock",
    "FixedMonotonicClock",
    "IdentityPort",
    "MonotonicClockPort",
    "RuntimeDependencies",
    "SecureIdentity",
    "SecureToken",
    "SequenceIdentity",
    "SequenceToken",
    "StructuredModelBudgetError",
    "StructuredModelError",
    "StructuredModelPort",
    "StructuredModelProviderError",
    "StructuredModelRequest",
    "StructuredModelResult",
    "StructuredModelTimeout",
    "StructuredModelValidationError",
    "SystemClock",
    "SystemMonotonicClock",
    "TokenPort",
    "deterministic_dependencies",
]
